# Render Configuration File
# This file defines how to deploy your services on Render

services:
  # Combined Frontend + Backend Service
  - type: web
    name: certificate-automation
    env: node
    plan: free
    buildCommand: |
      cd Backend && npm install &&
      cd ../Frontend/React && npm install && npm run build
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: certificate-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://certificate-automation-dmoe.onrender.com
      - key: VERIFICATION_BASE_URL
        value: https://certificate-automation-dmoe.onrender.com/verify/
      - key: TEMPLATE_PATH
        value: Backend/Certificate_Templates/
      - key: CERTIFICATE_OUTPUT_PATH
        value: Backend/Generated-Certificates/
      - key: FONT_PATH
        value: Backend/Certificate_Templates/fonts/
    autoDeploy: true

# Database
databases:
  - name: certificate-db
    plan: free
    databaseName: certificate_automation
    user: cert_user
