# Render Configuration File
# This file defines how to deploy your services on Render

services:
  # Combined Frontend + Backend Service
  - type: web
    name: certificate-automation
    env: node
    plan: free
    buildCommand: echo "Directory structure check..." && pwd && ls -la && echo "Installing root dependencies..." && npm install && echo "Installing frontend dependencies..." && cd Frontend/React && npm install && npm run build && echo "Build completed!"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://certificate_db_44nb_user:bjfK6mi1OXHXE0tYBw8YjtzrWOHX6EhM@dpg-d1p19f7fte5s73br93k0-a.oregon-postgres.render.com/certificate_db_44nb
      - key: FRONTEND_URL
        value: https://certificate-automation-dmoe.onrender.com
      - key: VERIFICATION_BASE_URL
        value: https://certificate-automation-dmoe.onrender.com/verify/
      - key: TEMPLATE_PATH
        value: Backend/Certificate_Templates/
      - key: CERTIFICATE_OUTPUT_PATH
        value: Backend/Generated-Certificates/
      - key: FONT_PATH
        value: Backend/Certificate_Templates/fonts/
      - key: SECRET_KEY
        value: production-secret-key-change-this
      - key: JWT_SECRET
        value: jwt-secret-key-change-this
      - key: BCRYPT_ROUNDS
        value: 12
    autoDeploy: true

# Database
databases:
  - name: certificate-db
    plan: free
    databaseName: certificate_automation
    user: cert_user
