import React from 'react';
import QRCode from 'qrcode.react';

const CertificateDisplay = ({ certificate, showQRCode = true, className = "" }) => {
  if (!certificate) {
    return (
      <div className="certificate-container">
        <div className="text-center text-gray-500">
          No certificate data available
        </div>
      </div>
    );
  }

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  return (
    <div className={`certificate-container ${className}`}>
      {/* Certificate Header */}
      <div className="certificate-header">
        <h1 className="certificate-title">Certificate of Achievement</h1>
        <p className="certificate-subtitle">This is to certify that</p>
      </div>

      {/* Certificate Body */}
      <div className="certificate-body">
        {/* Recipient Name */}
        <div className="text-center mb-6">
          <h2 className="text-4xl font-bold text-primary-600 mb-2">
            {certificate.name}
          </h2>
          <p className="text-lg text-gray-600">
            has successfully completed the program
          </p>
        </div>

        {/* Program Name */}
        <div className="text-center mb-8">
          <h3 className="text-2xl font-semibold text-gray-800 italic">
            "{certificate.program}"
          </h3>
        </div>

        {/* Certificate Details */}
        <div className="space-y-3 mb-6">
          <div className="certificate-field">
            <span className="certificate-label">Reference No:</span>
            <span className="certificate-value font-mono">{certificate.refNo}</span>
          </div>
          
          <div className="certificate-field">
            <span className="certificate-label">Certificate ID:</span>
            <span className="certificate-value font-mono">{certificate.dofNo}</span>
          </div>
          
          <div className="certificate-field">
            <span className="certificate-label">Issue Date:</span>
            <span className="certificate-value">{formatDate(certificate.issueDate)}</span>
          </div>

          {certificate.metadata?.verificationCount && (
            <div className="certificate-field">
              <span className="certificate-label">Times Verified:</span>
              <span className="certificate-value">{certificate.metadata.verificationCount}</span>
            </div>
          )}

          {certificate.metadata?.lastVerified && (
            <div className="certificate-field">
              <span className="certificate-label">Last Verified:</span>
              <span className="certificate-value">
                {formatDate(certificate.metadata.lastVerified)}
              </span>
            </div>
          )}
        </div>

        {/* QR Code */}
        {showQRCode && (
          <div className="qr-code-container">
            <div className="text-center">
              <p className="text-sm text-gray-600 mb-3">
                Scan QR Code to verify authenticity
              </p>
              {certificate.qrCodeUrl ? (
                <img 
                  src={certificate.qrCodeUrl} 
                  alt="Certificate QR Code"
                  className="mx-auto"
                />
              ) : certificate.verificationUrl ? (
                <QRCode 
                  value={certificate.verificationUrl}
                  size={150}
                  level="M"
                  includeMargin={true}
                />
              ) : (
                <div className="w-32 h-32 bg-gray-200 flex items-center justify-center mx-auto">
                  <span className="text-gray-500 text-sm">QR Code unavailable</span>
                </div>
              )}
              <p className="text-xs text-gray-500 mt-2">
                Certificate ID: {certificate.dofNo}
              </p>
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="text-center mt-8 pt-6 border-t border-gray-200">
          <p className="text-sm text-gray-500">
            This certificate is digitally verified and secure
          </p>
          <p className="text-xs text-gray-400 mt-1">
            Generated by CertifyPro System
          </p>
        </div>
      </div>
    </div>
  );
};

export default CertificateDisplay;
